name: planningpoker
description: A planning poker app.
publish_to: 'none'

version: 0.4.1+230

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  teb_package:
    #git:
    #  url: https://github.com/marcosmhs/teb_package.git
    #  ref: main
    path: ../teb_package
  
  build_runner: ^2.4.6
  json_theme: ^6.3.2
  intl: ^0.19.0
  flutter_localization: ^0.1.13
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.0.1
  firebase_database: ^11.0.1
  firebase_analytics: ^11.0.1
  
  cupertino_icons: ^1.0.2
  
  url_launcher: ^6.1.14
  http: ^1.2.1
  
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/dark_theme.json
    - assets/light_theme.json
    - assets/images/light_fibonacci.png
    - assets/images/light_tshirt.png
    - assets/images/dark_fibonacci.png
    - assets/images/dark_tshirt.png    
