name: planningpoker
description: A planning poker app.
publish_to: 'none'

version: 0.4.0+225

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  teb_package:
    #git:
    #  url: https://github.com/marcosmhs/teb_package.git
    #  ref: main
    path: ../teb_package
  
  build_runner: ^2.4.6
  json_theme: ^6.3.2
  intl: ^0.19.0
  flutter_localization: ^0.1.13
  #cloud_firestore: ^4.9.0
  cloud_firestore: ^5.0.1
  #firebase_auth: ^4.8.0
  firebase_auth: ^5.0.1
  #firebase_database: ^10.2.6
  firebase_database: ^11.0.1
  #firebase_analytics: ^10.6.1
  firebase_analytics: ^11.0.1
  
  cupertino_icons: ^1.0.2
  
  url_launcher: ^6.1.14
  #http: ^0.13.6
  http: ^1.2.1
  
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^2.0.0
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/dark_theme.json
    - assets/light_theme.json
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
