// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHDZWKhw0-_nXcAKTTOX0sXoiEw8fsjWk',
    appId: '1:926979793410:web:8ef2adc83eeaf440ad3d1b',
    messagingSenderId: '926979793410',
    projectId: 'planningpoker-teb',
    authDomain: 'planningpoker-teb.firebaseapp.com',
    storageBucket: 'planningpoker-teb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOxjq8anGpdPeif4woHU3Xx3p5QhYv6fc',
    appId: '1:926979793410:android:2d49b6251ab48ca6ad3d1b',
    messagingSenderId: '926979793410',
    projectId: 'planningpoker-teb',
    storageBucket: 'planningpoker-teb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHpXGnVa5q9NoTnLqaMTxN8VdRWkKWuA0',
    appId: '1:926979793410:ios:f7824cd3e49d43a1ad3d1b',
    messagingSenderId: '926979793410',
    projectId: 'planningpoker-teb',
    storageBucket: 'planningpoker-teb.appspot.com',
    iosBundleId: 'com.thatexoticname.planningpoker.planningpoker',
  );
}
